brand:
  name: Ifeoluwa Babatunde
menu-string: Menu

nav:
  - title: Tools and Skills
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Connect With Me
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Ifeoluwa Babatunde 2019

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/snifewawa' 
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/snifewawa'
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/ifeoluwababatunde/'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
